
language: python

python:
  - 3.2
  - 3.3
  - 3.4

install:
    - pip install scrutinizer-ocular coverage webtest httmock requests ppp_datamodel ppp_core nltk numpy
    - python -m nltk.downloader punkt

before_script:
  - ./dependencies.sh
  - ./setup.py install
  - python3 demo/Dataset.py
  - python3 demo/Learn.py

script:
  - coverage3 run run_tests.py

after_script:
  - ocular --data-file ".coverage"
