
language: python

python:
  - 3.2
  - 3.3
  - 3.4

install:
    - pip install scrutinizer-ocular coverage webtest httmock requests ppp_datamodel ppp_core nltk numpy
    - pip install -U scikit-learn
    - python -m nltk.downloader punkt
    - sudo apt-get install build-essential python3-dev python3-setuptools python3-numpy python3-scipy libatlas-dev libatlas3gf-base
    - sudo update-alternatives --set libblas.so.3 /usr/lib/atlas-base/atlas/libblas.so.3
    - sudo update-alternatives --set liblapack.so.3 /usr/lib/atlas-base/atlas/liblapack.so.3



before_script:
  - export PPP_ML_STANDALONE_CONFIG=$TRAVIS_BUILD_DIR/config.json
  - mkdir /tmp/ppp_nlp_standalone_data/
  - ./setup.py install
  - ./bootstrap.sh

script:
  - coverage3 run run_tests.py

after_script:
  - ocular --data-file ".coverage"
