
language: python

python:
  - 3.2
  - 3.3
  - 3.4

install:
    - pip install scrutinizer-ocular coverage webtest httmock requests ppp_datamodel ppp_core nltk numpy
    - python -m nltk.downloader punkt

before_script:
  - ./setup.py install
  - ./bootstrap.sh

script:
  - coverage3 run run_tests.py

after_script:
  - ocular --data-file ".coverage"
