
language: python

python:
  - 3.2
  - 3.3
  - 3.4

install:
    - sudo apt-get install python3-numpy libopenblas-dev libatlas-dev libatlas3gf-base
    - sudo apt-get install libblas-dev liblapack-dev
    - pip install scrutinizer-ocular webtest httmock requests ppp_datamodel ppp_core nltk numpy
    # Coveralls 4.0 doesn't support Python 3.2
    - if [ "$TRAVIS_PYTHON_VERSION" == "3.2" ]; then travis_retry pip install coverage==3.7.1; fi
    - if [ "$TRAVIS_PYTHON_VERSION" != "3.2" ]; then travis_retry pip install coverage; fi
    - pip install scipy scikit-learn
    - python -m nltk.downloader punkt


before_script:
  - export PPP_ML_STANDALONE_CONFIG=$TRAVIS_BUILD_DIR/config.json
  - mkdir /tmp/ppp_nlp_standalone_data/
  - ./setup.py install
  - ./bootstrap.sh

script:
  - coverage3 run run_tests.py

after_script:
  - ocular --data-file ".coverage"
